sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - 4.1.0
before_install:
  - npm i -g npm@^2.0.0
before_script:
  - npm prune
after_success:
  - if [[ $COMMAND = test:coverage ]]; then npm run test:coverage:upload; fi
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
