sudo: false
language: node_js
notifications:
  email: false
node_js:
  - 4
before_script:
  - npm prune
after_success:
  - if [[ $COMMAND = test:coverage ]]; then npm run test:coverage:upload; fi
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
